-- =======================================================
-- AZEEZ JEWELS ERP - FULL SUPABASE DATABASE SCHEMA SETUP
-- Copy and paste this script into Supabase SQL Editor:
-- https://supabase.com/dashboard/project/vdhnjmeyvbcbvdreltcb/sql/new
-- =======================================================

-- 1. CUSTOMERS TABLE
CREATE TABLE IF NOT EXISTS customers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_code TEXT,
    name TEXT NOT NULL,
    phone TEXT,
    email TEXT,
    address TEXT,
    notes TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. ITEMS (INVENTORY) TABLE
CREATE TABLE IF NOT EXISTS items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    barcode TEXT,
    item_name TEXT NOT NULL,
    category TEXT,
    gross_weight NUMERIC DEFAULT 0,
    net_weight NUMERIC DEFAULT 0,
    weight NUMERIC DEFAULT 0,
    purity TEXT,
    metal_type TEXT DEFAULT 'gold',
    making_charges NUMERIC DEFAULT 0,
    stone_type TEXT,
    hsn_code TEXT DEFAULT '711319',
    gst_rate NUMERIC DEFAULT 3,
    price_per_gram NUMERIC DEFAULT 0,
    net_price NUMERIC DEFAULT 0,
    stock_status TEXT DEFAULT 'in_stock',
    location TEXT,
    remarks TEXT,
    huid TEXT,
    quantity INT DEFAULT 1,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. BILLS TABLE
CREATE TABLE IF NOT EXISTS bills (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bill_no TEXT UNIQUE NOT NULL,
    bill_date DATE DEFAULT CURRENT_DATE,
    customer_id BIGINT REFERENCES customers(id) ON DELETE SET NULL,
    staff_id TEXT,
    sale_type TEXT DEFAULT 'gst',
    subtotal NUMERIC DEFAULT 0,
    gst_amount NUMERIC DEFAULT 0,
    grand_total NUMERIC DEFAULT 0,
    discount NUMERIC DEFAULT 0,
    payment_method TEXT,
    bill_status TEXT DEFAULT 'final',
    old_gold_amount NUMERIC DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. BILL_ITEMS TABLE
CREATE TABLE IF NOT EXISTS bill_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bill_id BIGINT REFERENCES bills(id) ON DELETE CASCADE,
    inventory_item_id BIGINT,
    barcode TEXT,
    category TEXT,
    item_name TEXT NOT NULL,
    huid TEXT,
    gross_weight NUMERIC DEFAULT 0,
    net_weight NUMERIC DEFAULT 0,
    weight NUMERIC DEFAULT 0,
    rate NUMERIC DEFAULT 0,
    making_charges NUMERIC DEFAULT 0,
    line_total NUMERIC DEFAULT 0,
    sl_no INT DEFAULT 1,
    metal_type TEXT DEFAULT 'gold',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. GOLD EXCHANGES (SCRAP BUYING VOUCHERS) TABLE
CREATE TABLE IF NOT EXISTS gold_exchanges (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reference_no TEXT UNIQUE NOT NULL,
    customer_name TEXT,
    customer_phone TEXT,
    particulars TEXT,
    description TEXT,
    hsn_code TEXT DEFAULT '7113',
    weight NUMERIC DEFAULT 0,
    net_weight NUMERIC DEFAULT 0,
    purity TEXT,
    rate NUMERIC DEFAULT 0,
    total NUMERIC DEFAULT 0,
    total_value NUMERIC DEFAULT 0,
    total_amount NUMERIC DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ALTERS TO ENSURE EXISTING TABLE HAS ALL REQUIRED COLUMNS
ALTER TABLE gold_exchanges ADD COLUMN IF NOT EXISTS particulars TEXT;
ALTER TABLE gold_exchanges ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE gold_exchanges ADD COLUMN IF NOT EXISTS weight NUMERIC DEFAULT 0;
ALTER TABLE gold_exchanges ADD COLUMN IF NOT EXISTS net_weight NUMERIC DEFAULT 0;
ALTER TABLE gold_exchanges ADD COLUMN IF NOT EXISTS purity TEXT;
ALTER TABLE gold_exchanges ADD COLUMN IF NOT EXISTS rate NUMERIC DEFAULT 0;
ALTER TABLE gold_exchanges ADD COLUMN IF NOT EXISTS total NUMERIC DEFAULT 0;
ALTER TABLE gold_exchanges ADD COLUMN IF NOT EXISTS total_value NUMERIC DEFAULT 0;
ALTER TABLE gold_exchanges ADD COLUMN IF NOT EXISTS total_amount NUMERIC DEFAULT 0;
ALTER TABLE gold_exchanges DISABLE ROW LEVEL SECURITY;

-- 6. GOLD RATES TABLE
CREATE TABLE IF NOT EXISTS gold_rates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    effective_date DATE DEFAULT CURRENT_DATE,
    metal_type TEXT NOT NULL,
    rate_per_gram NUMERIC NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT unique_date_metal UNIQUE (effective_date, metal_type)
);

-- 7. LAYAWAY TRANSACTIONS TABLE
CREATE TABLE IF NOT EXISTS layaway_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bill_id BIGINT REFERENCES bills(id) ON DELETE CASCADE,
    payment_date DATE DEFAULT CURRENT_DATE,
    amount NUMERIC DEFAULT 0,
    payment_method TEXT,
    reference_number TEXT,
    notes TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 8. ADVANCE BOOKINGS TABLE
CREATE TABLE IF NOT EXISTS advance_bookings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bill_id BIGINT REFERENCES bills(id) ON DELETE CASCADE,
    booking_date DATE DEFAULT CURRENT_DATE,
    delivery_date DATE,
    advance_amount NUMERIC DEFAULT 0,
    total_amount NUMERIC DEFAULT 0,
    remaining_amount NUMERIC DEFAULT 0,
    item_description TEXT,
    customer_notes TEXT,
    booking_status TEXT DEFAULT 'active',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 9. USERS TABLE
CREATE TABLE IF NOT EXISTS users (
    id TEXT PRIMARY KEY,
    username TEXT UNIQUE NOT NULL,
    password_hash TEXT NOT NULL,
    role TEXT NOT NULL DEFAULT 'staff',
    staff_code TEXT,
    can_edit_bills BOOLEAN DEFAULT FALSE,
    can_edit_stock BOOLEAN DEFAULT FALSE,
    can_authorize_nongst BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- SEED DEFAULT ADMIN AND STAFF USERS
INSERT INTO users (id, username, password_hash, role, staff_code, can_edit_bills, can_edit_stock, can_authorize_nongst)
VALUES 
  ('admin-001', 'admin', 'admin123', 'admin', 'ADM01', true, true, true),
  ('staff-001', 'staff', 'staff123', 'staff', 'STF01', false, false, false)
ON CONFLICT (username) DO NOTHING;

-- DISABLE ROW LEVEL SECURITY (RLS) ON PUBLIC TABLES TO ALLOW API KEY ACCESS
ALTER TABLE customers DISABLE ROW LEVEL SECURITY;
ALTER TABLE items DISABLE ROW LEVEL SECURITY;
ALTER TABLE bills DISABLE ROW LEVEL SECURITY;
ALTER TABLE bill_items DISABLE ROW LEVEL SECURITY;
ALTER TABLE gold_exchanges DISABLE ROW LEVEL SECURITY;
ALTER TABLE gold_rates DISABLE ROW LEVEL SECURITY;
ALTER TABLE layaway_transactions DISABLE ROW LEVEL SECURITY;
ALTER TABLE advance_bookings DISABLE ROW LEVEL SECURITY;
ALTER TABLE users DISABLE ROW LEVEL SECURITY;
