import React, { useState } from 'react';
import { X, Printer, Tag, Check, Sliders } from 'lucide-react';
import JsBarcode from 'jsbarcode';
import { Button } from './UIComponents';
import { Item } from '../types';

interface BarcodePrintModalProps {
  isOpen: boolean;
  onClose: () => void;
  item: Item | null;
}

export type TagSize = '50x12' | '81x12' | '100x15' | '100x20';

function getBarcodeSvgString(text: string): string {
  try {
    const svgNode = document.createElementNS("http://www.w3.org/2000/svg", "svg");
    JsBarcode(svgNode, text || 'AHS000000', {
      format: "CODE128",
      width: 1, // 1 unit per module
      height: 40,
      displayValue: false,
      margin: 0, // No quiet zone margin, let CSS handle spacing to save module width
      background: "transparent",
      lineColor: "#000000"
    });
    
    // Total modules dynamically generated by JsBarcode (e.g. 134 for 9 chars)
    let totalModules = 100;
    const viewBox = svgNode.getAttribute("viewBox");
    if (viewBox) {
      const parts = viewBox.split(' ');
      if (parts.length === 4) totalModules = parseFloat(parts[2]);
    } else {
      totalModules = parseFloat(svgNode.getAttribute("width") || "100");
    }

    // 203 DPI printer: 1 dot = 0.125mm.
    // By forcing the physical width to exactly match 1 dot per module, 
    // the printer driver prints the bars perfectly without dithering!
    const exactWidthMm = totalModules * 0.125;
    
    svgNode.setAttribute("style", `width: ${exactWidthMm}mm; height: 100%; max-height: 100%;`);
    svgNode.setAttribute("preserveAspectRatio", "none");
    svgNode.setAttribute("shape-rendering", "crispEdges");
    return svgNode.outerHTML;
  } catch (e) {
    console.error("JsBarcode generation error:", e);
    return `<svg viewBox="0 0 100 35"><rect width="100%" height="100%" fill="#fff"/></svg>`;
  }
}

export const BarcodePrintModal: React.FC<BarcodePrintModalProps> = ({
  isOpen,
  onClose,
  item
}) => {
  const [tagSize, setTagSize] = useState<TagSize>('100x15');
  const [printQuantity, setPrintQuantity] = useState<number>(1);
  const [showPrice, setShowPrice] = useState<boolean>(true);
  const [showHUID, setShowHUID] = useState<boolean>(true);
  const [tailPosition, setTailPosition] = useState<'right' | 'left'>('right');

  if (!isOpen || !item) return null;

  const handlePrint = () => {
    const printWindow = window.open('', '_blank');
    if (!printWindow) return;

    const labelDims = {
      '50x12': { width: 50, height: 12, halfW: 16, tailW: 18 },
      '81x12': { width: 81, height: 12, halfW: 26, tailW: 29 },
      '100x15': { width: 100, height: 15, halfW: 27.5, tailW: 45 },
      '100x20': { width: 100, height: 20, halfW: 36, tailW: 28 },
    }[tagSize]!;

    const barcodeText = (item.barcode || 'AHS000000').trim();
    const barcodeSvgHtml = getBarcodeSvgString(barcodeText);

    const flexDir = tailPosition === 'left' ? 'row-reverse' : 'row';
    const W = labelDims.width;
    const H = labelDims.height;
    const HW = labelDims.halfW;
    const TW = labelDims.tailW;

    const labelHtml = Array.from({ length: printQuantity }).map(() => `
      <div class="lc">
        <!-- LEFT HALF (Side 1: Brand, Barcode, SKU) -->
        <div class="half left-half">
          <div class="brand">AZEEZ JEWELS</div>
          <div class="bc-box">
            ${barcodeSvgHtml}
          </div>
          <div class="sku">${barcodeText}</div>
        </div>

        <!-- RIGHT HALF (Side 2: Details) -->
        <div class="half right-half">
          <div class="purity">${item.purity || '22K 916'}</div>
          <div class="item-name">${item.item_name}</div>
          <div class="weights">
            <div>Gr: ${(item.gross_weight || item.weight || 0).toFixed(3)}g</div>
            <div>Nt: ${(item.net_weight || item.weight || 0).toFixed(3)}g</div>
          </div>
          ${showHUID && item.huid ? `<div class="huid">HUID: ${item.huid}</div>` : ''}
          ${showPrice && item.net_price ? `<div class="price">₹ ${item.net_price.toLocaleString()}</div>` : ''}
        </div>

        <!-- TAIL -->
        <div class="tail"></div>
      </div>
    `).join('');

    printWindow.document.write(`<!DOCTYPE html>
<html>
<head>
<title></title>
<style>
@page {
  size: ${W}mm ${H}mm;
  margin: 0mm !important;
}
* { margin: 0; padding: 0; box-sizing: border-box; }
html, body {
  width: ${W}mm;
  height: ${H}mm;
  margin: 0 !important;
  padding: 0 !important;
  background: #fff;
  color: #000;
  font-family: Arial, Helvetica, sans-serif;
  -webkit-print-color-adjust: exact;
  print-color-adjust: exact;
  overflow: hidden;
}
.lc {
  width: ${W}mm;
  height: ${H}mm;
  display: flex;
  flex-direction: ${flexDir};
  align-items: stretch;
  page-break-after: always;
  page-break-inside: avoid;
  padding: 0.5mm 1mm;
  overflow: hidden;
  box-sizing: border-box;
}
.half {
  width: ${HW}mm;
  height: ${H - 1}mm;
  display: flex;
  flex-direction: column;
  justify-content: space-between;
  box-sizing: border-box;
  overflow: hidden;
}
.left-half {
  padding-right: 1mm;
  padding-left: 2mm; /* Shifted right to avoid printer dead-zone cutoff */
  align-items: center;
  text-align: center;
}
.right-half {
  padding-left: 2mm; /* Added more space from the fold line */
  padding-right: 0.5mm;
  justify-content: space-between;
}
.tail {
  width: ${TW}mm;
  flex-shrink: 0;
}
.brand {
  font-size: 1.6mm;
  font-weight: 900;
  letter-spacing: 0.1mm;
  line-height: 1;
  text-transform: uppercase;
  text-align: center;
  white-space: nowrap;
  overflow: hidden;
  width: 100%;
}
.bc-box {
  width: 100%;
  height: 6.8mm;
  display: flex;
  align-items: center;
  justify-content: center;
  overflow: hidden;
  margin: 0.2mm 0;
}
.bc-box svg {
  width: 100%;
  height: 100%;
}
.sku {
  font-family: monospace, monospace;
  font-size: 1.5mm;
  font-weight: 900;
  text-align: center;
  line-height: 1;
  letter-spacing: 0.1mm;
  white-space: nowrap;
  overflow: hidden;
  width: 100%;
}
.purity {
  font-size: 1.6mm;
  font-weight: 900;
  line-height: 1;
  color: #000;
  white-space: nowrap;
  overflow: hidden;
}
.item-name {
  font-size: 1.7mm;
  font-weight: bold;
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
  line-height: 1.1;
  text-transform: capitalize;
}
.weights {
  display: flex;
  flex-direction: column;
  gap: 0.3mm;
  font-size: 1.5mm;
  font-weight: bold;
  font-family: monospace, monospace;
  line-height: 1;
}
.huid {
  font-size: 1.5mm;
  font-weight: bold;
  line-height: 1;
  white-space: nowrap;
  overflow: hidden;
}
.price {
  font-size: 1.6mm;
  font-weight: 900;
  line-height: 1;
  white-space: nowrap;
  overflow: hidden;
}
@media print {
  html, body { width: ${W}mm !important; height: ${H}mm !important; }
  .lc { width: ${W}mm !important; height: ${H}mm !important; }
}
</style>
</head>
<body>
${labelHtml}
<script>
  setTimeout(() => {
    window.print();
    window.close();
  }, 300);
</script>
</body>
</html>`);
    printWindow.document.close();
  };

  return (
    <div className="fixed inset-0 z-[100] bg-charcoal-900/80 backdrop-blur-md flex items-center justify-center p-4">
      <div className="bg-white rounded-2xl shadow-2xl border border-app-border w-full max-w-xl overflow-hidden animate-in zoom-in-95">
        {/* MODAL HEADER */}
        <div className="bg-charcoal-900 px-6 py-4 flex justify-between items-center text-white">
          <div className="flex items-center gap-3">
            <div className="w-9 h-9 rounded-full bg-gold-500 text-charcoal-900 flex items-center justify-center font-bold">
              <Tag size={18} />
            </div>
            <div>
              <h3 className="font-bold text-base uppercase tracking-wide">Jewellery Barcode Tag Generator</h3>
              <p className="text-[10px] text-gold-500 uppercase tracking-widest font-bold">TSC TTP-244 Pro Thermal Printer</p>
            </div>
          </div>
          <button onClick={onClose} className="p-1.5 text-gray-400 hover:text-white rounded-full bg-white/10">
            <X size={20} />
          </button>
        </div>

        {/* MODAL BODY */}
        <div className="p-6 space-y-5">
          {/* TAG SIZE SELECTOR */}
          <div>
            <label className="block text-xs font-bold text-charcoal-800 uppercase tracking-wider mb-2">
              1. Select Physical Tag / Label Size
            </label>
            <div className="grid grid-cols-4 gap-2">
              {[
                { id: '50x12', label: '50mm × 12mm', desc: 'Standard Dumbbell' },
                { id: '81x12', label: '81mm × 12mm', desc: 'Extended Dumbbell' },
                { id: '100x15', label: '100mm × 15mm', desc: 'Chain / Necklace' },
                { id: '100x20', label: '100mm × 20mm', desc: 'Heavy Tag (HUID)' },
              ].map(size => (
                <button
                  key={size.id}
                  onClick={() => setTagSize(size.id as TagSize)}
                  className={`p-2.5 rounded-xl border text-left transition-all cursor-pointer ${tagSize === size.id
                    ? 'border-gold-500 bg-gold-50/70 shadow-sm ring-1 ring-gold-500'
                    : 'border-gray-200 hover:bg-gray-50'
                    }`}
                >
                  <div className="flex items-center justify-between">
                    <span className="font-bold text-xs text-charcoal-900">{size.label}</span>
                    {tagSize === size.id && <Check size={13} className="text-gold-600" />}
                  </div>
                  <p className="text-[9.5px] text-gray-500 mt-0.5 leading-tight">{size.desc}</p>
                </button>
              ))}
            </div>
          </div>

          {/* STICKER TAIL DIRECTION */}
          <div>
            <label className="block text-xs font-bold text-charcoal-800 uppercase tracking-wider mb-1.5">
              2. Sticker Tail Position
            </label>
            <div className="grid grid-cols-2 gap-3">
              {[
                { id: 'right', label: 'Tail Right (Standard Head Left)' },
                { id: 'left', label: 'Tail Left (Reversed Head Right)' }
              ].map((opt) => (
                <button
                  key={opt.id}
                  onClick={() => setTailPosition(opt.id as any)}
                  className={`py-2 px-3 rounded-xl text-xs font-bold border transition-all cursor-pointer text-left ${tailPosition === opt.id
                    ? 'border-gold-500 bg-gold-50 text-gold-800 shadow-sm ring-1 ring-gold-500'
                    : 'border-gray-200 text-gray-600 hover:bg-gray-50'
                    }`}
                >
                  {opt.label}
                </button>
              ))}
            </div>
          </div>

          {/* CRITICAL PRINTER SETTINGS BANNER */}
          <div className="bg-amber-50 border border-amber-200 rounded-xl p-3.5 text-xs text-amber-900 space-y-1.5">
            <div className="font-bold flex items-center gap-1.5 text-amber-800 uppercase tracking-wider text-[11px]">
              <Sliders size={14} className="text-amber-600" /> Key Chrome Settings & Printer Calibration (TSC TTP-244 Pro)
            </div>
            <ul className="list-disc list-inside space-y-0.5 text-[11px] font-medium text-amber-800">
              <li>In Chrome Print: Set <strong>Margins</strong> to <strong>None</strong> & Uncheck <strong>Headers & Footers</strong></li>
              <li><strong>TSC Driver Setup</strong>: In Windows <i>Devices & Printers → TSC TTP-244 Pro → Preferences</i>, set <strong>Media Type: Labels with Gaps</strong> (Gap: 2mm)</li>
              <li><strong>Calibrate Gap Sensor</strong>: Turn OFF printer, hold <strong>FEED button</strong>, turn ON until green LED blinks — this aligns physical sticker gaps perfectly!</li>
            </ul>
          </div>

          {/* PRINT OPTIONS & QUANTITY */}
          <div className="grid grid-cols-3 gap-4 items-center">
            <div>
              <label className="block text-xs font-bold text-charcoal-800 uppercase mb-1">Copies</label>
              <input
                type="number"
                min={1}
                max={50}
                value={printQuantity}
                onChange={(e) => setPrintQuantity(Math.max(1, parseInt(e.target.value) || 1))}
                className="w-full px-3 py-2 border border-gray-300 rounded-lg text-center font-mono font-bold"
              />
            </div>
            <div className="flex items-center gap-2 pt-5">
              <input
                type="checkbox"
                id="showHuidOpt"
                checked={showHUID}
                onChange={(e) => setShowHUID(e.target.checked)}
                className="w-4 h-4 accent-gold-500 rounded cursor-pointer"
              />
              <label htmlFor="showHuidOpt" className="text-xs font-bold text-charcoal-800 cursor-pointer">Include HUID</label>
            </div>
            <div className="flex items-center gap-2 pt-5">
              <input
                type="checkbox"
                id="showPriceOpt"
                checked={showPrice}
                onChange={(e) => setShowPrice(e.target.checked)}
                className="w-4 h-4 accent-gold-500 rounded cursor-pointer"
              />
              <label htmlFor="showPriceOpt" className="text-xs font-bold text-charcoal-800 cursor-pointer">Include Selling Price</label>
            </div>
          </div>
        </div>

        {/* MODAL FOOTER */}
        <div className="p-4 bg-gray-50 border-t border-gray-200 flex justify-between items-center">
          <button onClick={onClose} className="px-4 py-2 text-xs font-bold text-gray-600 hover:text-gray-900">
            Cancel
          </button>
          <Button onClick={handlePrint} className="shadow-lg">
            <Printer size={16} className="mr-2" /> Print Tag on TSC TTP-244 Pro
          </Button>
        </div>
      </div>
    </div>
  );
};
